- hosts: terraform-ansible
  tasks:
  - name: 'Criando o arquivo index.html'
    copy:
      dest: /home/azureuser/index.html
      content: <h1>Feito com terraform e ansible</h1>

  - name: 'Criando o servidor busybox'
    shell: "nohup busybox httpd -f -p 8080 &"